In [9]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

import utils.data_processing_bronze_table
import utils.data_processing_silver_table
import utils.data_processing_gold_table

## set up pyspark session

In [2]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/09/21 07:30:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

## set up config

In [10]:
# set up config
snapshot_date_str = "2023-01-01"

start_date_str = "2023-01-01"
end_date_str = "2024-12-01"

In [11]:
# generate list of dates to process
def generate_first_of_month_dates(start_date_str, end_date_str):
    # Convert the date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    # List to store the first of month dates
    first_of_month_dates = []

    # Start from the first of the month of the start_date
    current_date = datetime(start_date.year, start_date.month, 1)

    while current_date <= end_date:
        # Append the date in yyyy-mm-dd format
        first_of_month_dates.append(current_date.strftime("%Y-%m-%d"))
        
        # Move to the first of the next month
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return first_of_month_dates

dates_str_lst = generate_first_of_month_dates(start_date_str, end_date_str)
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01']

## Build Bronze Table

In [58]:
# create bronze datalake
bronze_lms_directory = "datamart/bronze/lms/"

bronze_clickstream_directory = "datamart/bronze/feature_clickstream/"
bronze_attributes_directory = "datamart/bronze/features_attributes/"
bronze_financials_directory = "datamart/bronze/featuresfinancials/"

if not os.path.exists(bronze_lms_directory):
    os.makedirs(bronze_lms_directory)

if not os.path.exists(bronze_clickstream_directory):
    os.makedirs(bronze_clickstream_directory)

if not os.path.exists(bronze_attributes_directory):
    os.makedirs(bronze_attributes_directory)

if not os.path.exists(bronze_financials_directory):
    os.makedirs(bronze_financials_directory)

In [36]:
# define the bronze file

lms_file = "data/lms_loan_daily.csv"
clickstream_file = "data/feature_clickstream.csv"
attributes_file = "data/features_attributes.csv"
financials_file = "data/features_financials.csv"

In [33]:
#reload lib after changing the code

import importlib
import utils.data_processing_bronze_table
importlib.reload(utils.data_processing_bronze_table)

In [37]:
# run bronze backfill for lms_file
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, lms_file, bronze_lms_directory, spark)

2023-01-01row count: 530
saved to: datamart/bronze/lms/bronze_daily_2023_01_01.csv
2023-02-01row count: 1031
saved to: datamart/bronze/lms/bronze_daily_2023_02_01.csv
2023-03-01row count: 1537
saved to: datamart/bronze/lms/bronze_daily_2023_03_01.csv
2023-04-01row count: 2047
saved to: datamart/bronze/lms/bronze_daily_2023_04_01.csv
2023-05-01row count: 2568
saved to: datamart/bronze/lms/bronze_daily_2023_05_01.csv
2023-06-01row count: 3085
saved to: datamart/bronze/lms/bronze_daily_2023_06_01.csv
2023-07-01row count: 3556
saved to: datamart/bronze/lms/bronze_daily_2023_07_01.csv
2023-08-01row count: 4037
saved to: datamart/bronze/lms/bronze_daily_2023_08_01.csv
2023-09-01row count: 4491
saved to: datamart/bronze/lms/bronze_daily_2023_09_01.csv
2023-10-01row count: 4978
saved to: datamart/bronze/lms/bronze_daily_2023_10_01.csv
2023-11-01row count: 5469
saved to: datamart/bronze/lms/bronze_daily_2023_11_01.csv
2023-12-01row count: 5428
saved to: datamart/bronze/lms/bronze_daily_2023_12_01.csv
2024-01-01row count: 5412
saved to: datamart/bronze/lms/bronze_daily_2024_01_01.csv
2024-02-01row count: 5424
saved to: datamart/bronze/lms/bronze_daily_2024_02_01.csv
2024-03-01row count: 5425
saved to: datamart/bronze/lms/bronze_daily_2024_03_01.csv
2024-04-01row count: 5417
saved to: datamart/bronze/lms/bronze_daily_2024_04_01.csv
2024-05-01row count: 5391
saved to: datamart/bronze/lms/bronze_daily_2024_05_01.csv
2024-06-01row count: 5418
saved to: datamart/bronze/lms/bronze_daily_2024_06_01.csv
2024-07-01row count: 5442
saved to: datamart/bronze/lms/bronze_daily_2024_07_01.csv
2024-08-01row count: 5531
saved to: datamart/bronze/lms/bronze_daily_2024_08_01.csv
2024-09-01row count: 5537
saved to: datamart/bronze/lms/bronze_daily_2024_09_01.csv
2024-10-01row count: 5502
saved to: datamart/bronze/lms/bronze_daily_2024_10_01.csv
2024-11-01row count: 5501
saved to: datamart/bronze/lms/bronze_daily_2024_11_01.csv
2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_daily_2024_12_01.csv

In [18]:
# inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, lms_file, bronze_lms_directory, spark).toPandas()

2024-12-01row count: 5531
saved to: datamart/bronze/lms/bronze_loan_daily_2024_12_01.csv

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date
0,CUS_0x100b_2024_03_01,CUS_0x100b,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01
1,CUS_0x102e_2024_04_01,CUS_0x102e,2024-04-01,10,8,10000,1000.0,0.0,6000.0,8000.0,2024-12-01
2,CUS_0x1038_2024_10_01,CUS_0x1038,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
3,CUS_0x103e_2024_12_01,CUS_0x103e,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
4,CUS_0x1048_2024_02_01,CUS_0x1048,2024-02-01,10,10,10000,1000.0,0.0,9000.0,9000.0,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...
5526,CUS_0xfe3_2024_04_01,CUS_0xfe3,2024-04-01,10,8,10000,1000.0,1000.0,0.0,2000.0,2024-12-01
5527,CUS_0xff3_2024_06_01,CUS_0xff3,2024-06-01,10,6,10000,1000.0,1000.0,0.0,4000.0,2024-12-01
5528,CUS_0xff4_2024_12_01,CUS_0xff4,2024-12-01,10,0,10000,0.0,0.0,0.0,10000.0,2024-12-01
5529,CUS_0xff6_2024_10_01,CUS_0xff6,2024-10-01,10,2,10000,1000.0,1000.0,0.0,8000.0,2024-12-01
5530,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000,1000.0,1000.0,0.0,1000.0,2024-12-01

In [38]:
# run bronze backfill for feature files
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, clickstream_file, bronze_clickstream_directory, spark)

2023-01-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_01_01.csv
2023-02-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_02_01.csv
2023-03-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_03_01.csv
2023-04-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_04_01.csv
2023-05-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_05_01.csv
2023-06-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_06_01.csv
2023-07-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_07_01.csv
2023-08-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_08_01.csv
2023-09-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_09_01.csv
2023-10-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_10_01.csv
2023-11-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_11_01.csv
2023-12-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2023_12_01.csv
2024-01-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_01_01.csv
2024-02-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_02_01.csv
2024-03-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_03_01.csv
2024-04-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_04_01.csv
2024-05-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_05_01.csv
2024-06-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_06_01.csv
2024-07-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_07_01.csv
2024-08-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_08_01.csv
2024-09-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_09_01.csv
2024-10-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_10_01.csv
2024-11-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_11_01.csv
2024-12-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_daily_2024_12_01.csv

In [30]:
#Inspect output
utils.data_processing_bronze_table.process_bronze_table(date_str, clickstream_file, bronze_clickstream_directory, spark).toPandas()

2024-12-01row count: 8974
saved to: datamart/bronze/feature_clickstream/bronze_loan_daily_2024_12_01.csv

,fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,fe_10,...,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20,Customer_ID,snapshot_date
0,145,189,109,134,196,-37,101,82,111,24,...,65,249,200,185,-83,-18,-76,30,CUS_0x1037,2024-12-01
1,40,184,187,75,192,146,38,109,353,141,...,-14,193,125,117,215,91,33,255,CUS_0x1069,2024-12-01
2,98,121,180,200,95,48,59,194,76,84,...,167,101,92,185,98,68,-60,116,CUS_0x114a,2024-12-01
3,85,96,19,47,30,39,-32,210,-81,206,...,143,94,139,237,78,187,77,33,CUS_0x1184,2024-12-01
4,98,45,155,56,112,47,52,138,153,225,...,-43,142,121,10,189,110,264,241,CUS_0x1297,2024-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8969,414,22,72,57,142,192,11,139,24,63,...,179,91,20,189,-35,-19,15,66,CUS_0xdf6,2024-12-01
8970,116,-124,-108,212,-21,227,146,112,186,-65,...,38,226,319,98,9,152,17,14,CUS_0xe23,2024-12-01
8971,237,-3,-49,375,144,41,-170,324,19,266,...,7,102,64,191,124,220,231,75,CUS_0xe4e,2024-12-01
8972,5,67,211,83,207,-41,325,14,-18,41,...,109,266,28,157,131,116,101,131,CUS_0xedd,2024-12-01
8973,196,11,115,94,167,227,119,255,32,96,...,120,85,363,74,-26,107,104,186,CUS_0xfe4,2024-12-01

In [39]:
# run bronze backfill for feature attributes file
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, attributes_file, bronze_attributes_directory, spark)

2023-01-01row count: 530
saved to: datamart/bronze/features_attributes/bronze_daily_2023_01_01.csv
2023-02-01row count: 501
saved to: datamart/bronze/features_attributes/bronze_daily_2023_02_01.csv
2023-03-01row count: 506
saved to: datamart/bronze/features_attributes/bronze_daily_2023_03_01.csv
2023-04-01row count: 510
saved to: datamart/bronze/features_attributes/bronze_daily_2023_04_01.csv
2023-05-01row count: 521
saved to: datamart/bronze/features_attributes/bronze_daily_2023_05_01.csv
2023-06-01row count: 517
saved to: datamart/bronze/features_attributes/bronze_daily_2023_06_01.csv
2023-07-01row count: 471
saved to: datamart/bronze/features_attributes/bronze_daily_2023_07_01.csv
2023-08-01row count: 481
saved to: datamart/bronze/features_attributes/bronze_daily_2023_08_01.csv
2023-09-01row count: 454
saved to: datamart/bronze/features_attributes/bronze_daily_2023_09_01.csv
2023-10-01row count: 487
saved to: datamart/bronze/features_attributes/bronze_daily_2023_10_01.csv
2023-11-01row count: 491
saved to: datamart/bronze/features_attributes/bronze_daily_2023_11_01.csv
2023-12-01row count: 489
saved to: datamart/bronze/features_attributes/bronze_daily_2023_12_01.csv
2024-01-01row count: 485
saved to: datamart/bronze/features_attributes/bronze_daily_2024_01_01.csv
2024-02-01row count: 518
saved to: datamart/bronze/features_attributes/bronze_daily_2024_02_01.csv
2024-03-01row count: 511
saved to: datamart/bronze/features_attributes/bronze_daily_2024_03_01.csv
2024-04-01row count: 513
saved to: datamart/bronze/features_attributes/bronze_daily_2024_04_01.csv
2024-05-01row count: 491
saved to: datamart/bronze/features_attributes/bronze_daily_2024_05_01.csv
2024-06-01row count: 498
saved to: datamart/bronze/features_attributes/bronze_daily_2024_06_01.csv
2024-07-01row count: 505
saved to: datamart/bronze/features_attributes/bronze_daily_2024_07_01.csv
2024-08-01row count: 543
saved to: datamart/bronze/features_attributes/bronze_daily_2024_08_01.csv
2024-09-01row count: 493
saved to: datamart/bronze/features_attributes/bronze_daily_2024_09_01.csv
2024-10-01row count: 456
saved to: datamart/bronze/features_attributes/bronze_daily_2024_10_01.csv
2024-11-01row count: 488
saved to: datamart/bronze/features_attributes/bronze_daily_2024_11_01.csv
2024-12-01row count: 515
saved to: datamart/bronze/features_attributes/bronze_daily_2024_12_01.csv

In [40]:
# run bronze backfill for feature financials file
for date_str in dates_str_lst:
    utils.data_processing_bronze_table.process_bronze_table(date_str, financials_file, bronze_financials_directory, spark)

2023-01-01row count: 530
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_01_01.csv
2023-02-01row count: 501
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_02_01.csv
2023-03-01row count: 506
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_03_01.csv
2023-04-01row count: 510
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_04_01.csv
2023-05-01row count: 521
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_05_01.csv
2023-06-01row count: 517
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_06_01.csv
2023-07-01row count: 471
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_07_01.csv
2023-08-01row count: 481
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_08_01.csv
2023-09-01row count: 454
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_09_01.csv
2023-10-01row count: 487
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_10_01.csv
2023-11-01row count: 491
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_11_01.csv
2023-12-01row count: 489
saved to: datamart/bronze/featuresfinancials/bronze_daily_2023_12_01.csv
2024-01-01row count: 485
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_01_01.csv
2024-02-01row count: 518
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_02_01.csv
2024-03-01row count: 511
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_03_01.csv
2024-04-01row count: 513
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_04_01.csv
2024-05-01row count: 491
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_05_01.csv
2024-06-01row count: 498
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_06_01.csv
2024-07-01row count: 505
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_07_01.csv
2024-08-01row count: 543
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_08_01.csv
2024-09-01row count: 493
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_09_01.csv
2024-10-01row count: 456
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_10_01.csv
2024-11-01row count: 488
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_11_01.csv
2024-12-01row count: 515
saved to: datamart/bronze/featuresfinancials/bronze_daily_2024_12_01.csv

## Build Silver Table

In [46]:
#Load silver data processing lms

import utils.data_processing_silver_table_lms

In [60]:
import utils.data_processing_silver_table_attributes

In [54]:
# create silver datalake for lms
silver_lms_daily_directory = "datamart/silver/lms_loan_daily/"

if not os.path.exists(silver_lms_daily_directory):
    os.makedirs(silver_lms_daily_directory)

In [55]:
# run silver backfill for lms
for date_str in dates_str_lst:
    utils.data_processing_silver_table_lms.process_silver_table(date_str, bronze_lms_directory, silver_lms_daily_directory, spark)

loaded from: datamart/bronze/lms/bronze_daily_2023_01_01.csv row count: 530
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_01_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_02_01.csv row count: 1031
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_02_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_03_01.csv row count: 1537
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_03_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_04_01.csv row count: 2047
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_04_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_05_01.csv row count: 2568
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_05_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_06_01.csv row count: 3085
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_06_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_07_01.csv row count: 3556
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_07_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_08_01.csv row count: 4037
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_08_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_09_01.csv row count: 4491
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_09_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_10_01.csv row count: 4978
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_10_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_11_01.csv row count: 5469
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_11_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2023_12_01.csv row count: 5428
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2023_12_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_01_01.csv row count: 5412
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_01_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_02_01.csv row count: 5424
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_02_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_03_01.csv row count: 5425
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_03_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_04_01.csv row count: 5417
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_04_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_05_01.csv row count: 5391
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_05_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_06_01.csv row count: 5418
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_06_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_07_01.csv row count: 5442
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_07_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_08_01.csv row count: 5531
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_08_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_09_01.csv row count: 5537
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_09_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_10_01.csv row count: 5502
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_10_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_11_01.csv row count: 5501
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_11_01.parquet
loaded from: datamart/bronze/lms/bronze_daily_2024_12_01.csv row count: 5531
saved to: datamart/silver/lms_loan_daily/silver_loan_daily_2024_12_01.parquet

In [51]:
utils.data_processing_silver_table_lms.process_silver_table(date_str, bronze_lms_directory, silver_loan_daily_directory, spark).toPandas()

loaded from: datamart/bronze/lms/bronze_daily_2024_12_01.csv row count: 5531
saved to: datamart/silver/loan_daily/silver_loan_daily_2024_12_01.parquet

,loan_id,Customer_ID,loan_start_date,tenure,installment_num,loan_amt,due_amt,paid_amt,overdue_amt,balance,snapshot_date,mob,installments_missed,first_missed_date,dpd
0,CUS_0x100b_2024_03_01,CUS_0x100b,2024-03-01,10,9,10000.0,1000.0,1000.0,0.0,1000.0,2024-12-01,9,0,None,0
1,CUS_0x102e_2024_04_01,CUS_0x102e,2024-04-01,10,8,10000.0,1000.0,0.0,6000.0,8000.0,2024-12-01,8,6,2024-06-01,183
2,CUS_0x1038_2024_10_01,CUS_0x1038,2024-10-01,10,2,10000.0,1000.0,1000.0,0.0,8000.0,2024-12-01,2,0,None,0
3,CUS_0x103e_2024_12_01,CUS_0x103e,2024-12-01,10,0,10000.0,0.0,0.0,0.0,10000.0,2024-12-01,0,0,None,0
4,CUS_0x1048_2024_02_01,CUS_0x1048,2024-02-01,10,10,10000.0,1000.0,0.0,9000.0,9000.0,2024-12-01,10,9,2024-03-01,275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5526,CUS_0xfe3_2024_04_01,CUS_0xfe3,2024-04-01,10,8,10000.0,1000.0,1000.0,0.0,2000.0,2024-12-01,8,0,None,0
5527,CUS_0xff3_2024_06_01,CUS_0xff3,2024-06-01,10,6,10000.0,1000.0,1000.0,0.0,4000.0,2024-12-01,6,0,None,0
5528,CUS_0xff4_2024_12_01,CUS_0xff4,2024-12-01,10,0,10000.0,0.0,0.0,0.0,10000.0,2024-12-01,0,0,None,0
5529,CUS_0xff6_2024_10_01,CUS_0xff6,2024-10-01,10,2,10000.0,1000.0,1000.0,0.0,8000.0,2024-12-01,2,0,None,0
5530,CUS_0xffd_2024_03_01,CUS_0xffd,2024-03-01,10,9,10000.0,1000.0,1000.0,0.0,1000.0,2024-12-01,9,0,None,0

In [ ]:
# create silver datalake for lms
silver_attributes_daily_directory = "datamart/silver/features_attributes/"

if not os.path.exists(silver_attributes_daily_directory):
    os.makedirs(silver_attributes_daily_directory)

In [62]:
importlib.reload(utils.data_processing_silver_table_attributes)

In [63]:
# run silver backfill for attributes
for date_str in dates_str_lst:
    utils.data_processing_silver_table_attributes.process_silver_table(date_str, bronze_attributes_directory, silver_attributes_daily_directory, spark)

loaded from: datamart/bronze/features_attributes/bronze_daily_2023_01_01.csv row count: 530
saved to: datamart/silver/features_attributes/silver_daily_2023_01_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_02_01.csv row count: 501
saved to: datamart/silver/features_attributes/silver_daily_2023_02_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_03_01.csv row count: 506
saved to: datamart/silver/features_attributes/silver_daily_2023_03_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_04_01.csv row count: 510
saved to: datamart/silver/features_attributes/silver_daily_2023_04_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_05_01.csv row count: 521
saved to: datamart/silver/features_attributes/silver_daily_2023_05_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_06_01.csv row count: 517
saved to: datamart/silver/features_attributes/silver_daily_2023_06_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_07_01.csv row count: 471
saved to: datamart/silver/features_attributes/silver_daily_2023_07_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_08_01.csv row count: 481
saved to: datamart/silver/features_attributes/silver_daily_2023_08_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_09_01.csv row count: 454
saved to: datamart/silver/features_attributes/silver_daily_2023_09_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_10_01.csv row count: 487
saved to: datamart/silver/features_attributes/silver_daily_2023_10_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_11_01.csv row count: 491
saved to: datamart/silver/features_attributes/silver_daily_2023_11_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2023_12_01.csv row count: 489
saved to: datamart/silver/features_attributes/silver_daily_2023_12_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_01_01.csv row count: 485
saved to: datamart/silver/features_attributes/silver_daily_2024_01_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_02_01.csv row count: 518
saved to: datamart/silver/features_attributes/silver_daily_2024_02_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_03_01.csv row count: 511
saved to: datamart/silver/features_attributes/silver_daily_2024_03_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_04_01.csv row count: 513
saved to: datamart/silver/features_attributes/silver_daily_2024_04_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_05_01.csv row count: 491
saved to: datamart/silver/features_attributes/silver_daily_2024_05_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_06_01.csv row count: 498
saved to: datamart/silver/features_attributes/silver_daily_2024_06_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_07_01.csv row count: 505
saved to: datamart/silver/features_attributes/silver_daily_2024_07_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_08_01.csv row count: 543
saved to: datamart/silver/features_attributes/silver_daily_2024_08_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_09_01.csv row count: 493
saved to: datamart/silver/features_attributes/silver_daily_2024_09_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_10_01.csv row count: 456
saved to: datamart/silver/features_attributes/silver_daily_2024_10_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_11_01.csv row count: 488
saved to: datamart/silver/features_attributes/silver_daily_2024_11_01.parquet
loaded from: datamart/bronze/features_attributes/bronze_daily_2024_12_01.csv row count: 515
saved to: datamart/silver/features_attributes/silver_daily_2024_12_01.parquet

In [64]:
utils.data_processing_silver_table_attributes.process_silver_table(date_str, bronze_attributes_directory, silver_attributes_daily_directory, spark).toPandas()

loaded from: datamart/bronze/features_attributes/bronze_daily_2024_12_01.csv row count: 515
saved to: datamart/silver/features_attributes/silver_daily_2024_12_01.parquet

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date
0,CUS_0x103e,Tim Kellyf,40,155-72-8070,Scientist,2024-12-01
1,CUS_0x1195,Alexk,31,822-48-3629,Manager,2024-12-01
2,CUS_0x1197,Nayako,28,799-23-8283,Unspecified,2024-12-01
3,CUS_0x11e2,Valetkevitchr,34,809-04-1419,Musician,2024-12-01
4,CUS_0x11ec,William Schombergh,34,417-74-2163,Journalist,2024-12-01
...,...,...,...,...,...,...
510,CUS_0xe6c,Doris Frankelh,26,172-24-1577,Entrepreneur,2024-12-01
511,CUS_0xe99,Moone,48,164-90-3178,Mechanic,2024-12-01
512,CUS_0xf55,Tarmo Virkip,39,025-54-8593,Entrepreneur,2024-12-01
513,CUS_0xfd1,Frewy,32,389-55-6408,Architect,2024-12-01
514,CUS_0xff4,Poornimaf,37,655-05-7666,Entrepreneur,2024-12-01

## EDA on credit labels

In [1]:
# set dpd label definition
dpd = 30

# Path to the folder containing CSV files
folder_path = silver_loan_daily_directory

# Read all CSV files into a single DataFrame
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df = spark.read.option("header", "true").parquet(*files_list)

# filter only completed loans
df = df.filter(col("loan_start_date") < datetime.strptime("2024-01-01", "%Y-%m-%d"))

# create dpd flag if more than dpd
df = df.withColumn("dpd_flag", F.when(col("dpd") >= dpd, 1).otherwise(0))

# actual bads 
actual_bads_df = df.filter(col("installment_num") == 10)

# prepare for analysis
# df = df.filter(col("installment_num") < 10)

# visualise bad rate
pdf = df.toPandas()

# Group by col_A and count occurrences in col_B
grouped = pdf.groupby('mob')['dpd_flag'].mean()

# Sort the index (x-axis) of the grouped DataFrame
grouped = grouped.sort_index()

# Plotting
grouped.plot(kind='line', marker='o')

plt.title('DPD: '+ str(dpd))
plt.xlabel('mob')
plt.ylabel('bad rate')
plt.grid(True)
plt.show()

NameError: name 'silver_loan_daily_directory' is not defined

In [12]:
df.show()

+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+---+-------------------+-----------------+---+--------+
|             loan_id|Customer_ID|loan_start_date|tenure|installment_num|loan_amt|due_amt|paid_amt|overdue_amt|balance|snapshot_date|mob|installments_missed|first_missed_date|dpd|dpd_flag|
+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+---+-------------------+-----------------+---+--------+
|CUS_0x1011_2023_1...| CUS_0x1011|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
|CUS_0x1013_2023_1...| CUS_0x1013|     2023-12-01|    10|              9| 10000.0| 1000.0|  1000.0|        0.0| 1000.0|   2024-09-01|  9|                  0|             NULL|  0|       0|
|CUS_0x1018_2023_1...| CUS_0x1018|     2023-11-01|    10|             10| 10000.0| 1000.0|     0.0|     7000.0| 7000.0|   2024-09-01| 10|                  7|       2024-02-01|213|       1|
|CUS_0x1041_2023_1...| CUS_0x1041|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
|CUS_0x104a_2023_1...| CUS_0x104a|     2023-12-01|    10|              9| 10000.0| 1000.0|  1000.0|        0.0| 1000.0|   2024-09-01|  9|                  0|             NULL|  0|       0|
|CUS_0x105b_2023_1...| CUS_0x105b|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
|CUS_0x1063_2023_1...| CUS_0x1063|     2023-12-01|    10|              9| 10000.0| 1000.0|  1000.0|        0.0| 1000.0|   2024-09-01|  9|                  0|             NULL|  0|       0|
|CUS_0x107c_2023_1...| CUS_0x107c|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
|CUS_0x10d7_2023_1...| CUS_0x10d7|     2023-12-01|    10|              9| 10000.0| 1000.0|     0.0|     6000.0| 7000.0|   2024-09-01|  9|                  6|       2024-03-01|184|       1|
|CUS_0x10fd_2023_1...| CUS_0x10fd|     2023-12-01|    10|              9| 10000.0| 1000.0|     0.0|     6000.0| 7000.0|   2024-09-01|  9|                  6|       2024-03-01|184|       1|
|CUS_0x1107_2023_1...| CUS_0x1107|     2023-11-01|    10|             10| 10000.0| 1000.0|     0.0|    10000.0|10000.0|   2024-09-01| 10|                 10|       2023-11-01|305|       1|
|CUS_0x1139_2023_1...| CUS_0x1139|     2023-12-01|    10|              9| 10000.0| 1000.0|  1000.0|        0.0| 1000.0|   2024-09-01|  9|                  0|             NULL|  0|       0|
|CUS_0x117f_2023_1...| CUS_0x117f|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
|CUS_0x11a4_2023_1...| CUS_0x11a4|     2023-11-01|    10|             10| 10000.0| 1000.0|     0.0|     8000.0| 8000.0|   2024-09-01| 10|                  8|       2024-01-01|244|       1|
|CUS_0x1207_2023_1...| CUS_0x1207|     2023-12-01|    10|              9| 10000.0| 1000.0|     0.0|     6000.0| 7000.0|   2024-09-01|  9|                  6|       2024-03-01|184|       1|
|CUS_0x123d_2023_1...| CUS_0x123d|     2023-11-01|    10|             10| 10000.0| 1000.0|     0.0|     8000.0| 8000.0|   2024-09-01| 10|                  8|       2024-01-01|244|       1|
|CUS_0x1250_2023_1...| CUS_0x1250|     2023-12-01|    10|              9| 10000.0| 1000.0|  1000.0|        0.0| 1000.0|   2024-09-01|  9|                  0|             NULL|  0|       0|
|CUS_0x1281_2023_1...| CUS_0x1281|     2023-11-01|    10|             10| 10000.0| 1000.0|     0.0|     7000.0| 7000.0|   2024-09-01| 10|                  7|       2024-02-01|213|       1|
|CUS_0x12f2_2023_1...| CUS_0x12f2|     2023-12-01|    10|              9| 10000.0| 1000.0|     0.0|     5000.0| 6000.0|   2024-09-01|  9|                  5|       2024-04-01|153|       1|
|CUS_0x12fa_2023_1...| CUS_0x12fa|     2023-11-01|    10|             10| 10000.0| 1000.0|  1000.0|        0.0|    0.0|   2024-09-01| 10|                  0|             NULL|  0|       0|
+--------------------+-----------+---------------+------+---------------+--------+-------+--------+-----------+-------+-------------+---+-------------------+-----------------+---+--------+
only showing top 20 rows

## Build gold table for labels

In [13]:
# create bronze datalake
gold_label_store_directory = "datamart/gold/label_store/"

if not os.path.exists(gold_label_store_directory):
    os.makedirs(gold_label_store_directory)

In [14]:
# run gold backfill
for date_str in dates_str_lst:
    utils.data_processing_gold_table.process_labels_gold_table(date_str, silver_loan_daily_directory, gold_label_store_directory, spark, dpd = 30, mob = 6)

loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_01_01.parquet row count: 530
saved to: datamart/gold/label_store/gold_label_store_2023_01_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_02_01.parquet row count: 1031
saved to: datamart/gold/label_store/gold_label_store_2023_02_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_03_01.parquet row count: 1537
saved to: datamart/gold/label_store/gold_label_store_2023_03_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_04_01.parquet row count: 2047
saved to: datamart/gold/label_store/gold_label_store_2023_04_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_05_01.parquet row count: 2568
saved to: datamart/gold/label_store/gold_label_store_2023_05_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_06_01.parquet row count: 3085
saved to: datamart/gold/label_store/gold_label_store_2023_06_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_07_01.parquet row count: 3556
saved to: datamart/gold/label_store/gold_label_store_2023_07_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_08_01.parquet row count: 4037
saved to: datamart/gold/label_store/gold_label_store_2023_08_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_09_01.parquet row count: 4491
saved to: datamart/gold/label_store/gold_label_store_2023_09_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_10_01.parquet row count: 4978
saved to: datamart/gold/label_store/gold_label_store_2023_10_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_11_01.parquet row count: 5469

saved to: datamart/gold/label_store/gold_label_store_2023_11_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2023_12_01.parquet row count: 5428
saved to: datamart/gold/label_store/gold_label_store_2023_12_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_01_01.parquet row count: 5412
saved to: datamart/gold/label_store/gold_label_store_2024_01_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_02_01.parquet row count: 5424
saved to: datamart/gold/label_store/gold_label_store_2024_02_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_03_01.parquet row count: 5425

saved to: datamart/gold/label_store/gold_label_store_2024_03_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_04_01.parquet row count: 5417

saved to: datamart/gold/label_store/gold_label_store_2024_04_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_05_01.parquet row count: 5391
saved to: datamart/gold/label_store/gold_label_store_2024_05_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_06_01.parquet row count: 5418
saved to: datamart/gold/label_store/gold_label_store_2024_06_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_07_01.parquet row count: 5442
saved to: datamart/gold/label_store/gold_label_store_2024_07_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_08_01.parquet row count: 5531
saved to: datamart/gold/label_store/gold_label_store_2024_08_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_09_01.parquet row count: 5537
saved to: datamart/gold/label_store/gold_label_store_2024_09_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_10_01.parquet row count: 5502
saved to: datamart/gold/label_store/gold_label_store_2024_10_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_11_01.parquet row count: 5501
saved to: datamart/gold/label_store/gold_label_store_2024_11_01.parquet
loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_12_01.parquet row count: 5531
saved to: datamart/gold/label_store/gold_label_store_2024_12_01.parquet

In [15]:
utils.data_processing_gold_table.process_labels_gold_table(date_str, silver_loan_daily_directory, gold_label_store_directory, spark, dpd = 30, mob = 6).dtypes

loaded from: datamart/silver/loan_daily/silver_loan_daily_2024_12_01.parquet row count: 5531

saved to: datamart/gold/label_store/gold_label_store_2024_12_01.parquet

[('loan_id', 'string'),
 ('Customer_ID', 'string'),
 ('label', 'int'),
 ('label_def', 'string'),
 ('snapshot_date', 'date')]

## inspect label store

In [16]:
folder_path = gold_label_store_directory
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
df = spark.read.option("header", "true").parquet(*files_list)
print("row_count:",df.count())

df.show()

row_count: 8974
+--------------------+-----------+-----+----------+-------------+
|             loan_id|Customer_ID|label| label_def|snapshot_date|
+--------------------+-----------+-----+----------+-------------+
|CUS_0x1037_2023_0...| CUS_0x1037|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1069_2023_0...| CUS_0x1069|    0|30dpd_6mob|   2023-07-01|
|CUS_0x114a_2023_0...| CUS_0x114a|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1184_2023_0...| CUS_0x1184|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1297_2023_0...| CUS_0x1297|    1|30dpd_6mob|   2023-07-01|
|CUS_0x12fb_2023_0...| CUS_0x12fb|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1325_2023_0...| CUS_0x1325|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1341_2023_0...| CUS_0x1341|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1375_2023_0...| CUS_0x1375|    1|30dpd_6mob|   2023-07-01|
|CUS_0x13a8_2023_0...| CUS_0x13a8|    0|30dpd_6mob|   2023-07-01|
|CUS_0x13ef_2023_0...| CUS_0x13ef|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1440_2023_0...| CUS_0x1440|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1443_2023_0...| CUS_0x1443|    0|30dpd_6mob|   2023-07-01|
|CUS_0x145a_2023_0...| CUS_0x145a|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1492_2023_0...| CUS_0x1492|    0|30dpd_6mob|   2023-07-01|
|CUS_0x153d_2023_0...| CUS_0x153d|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1567_2023_0...| CUS_0x1567|    0|30dpd_6mob|   2023-07-01|
|CUS_0x15ad_2023_0...| CUS_0x15ad|    1|30dpd_6mob|   2023-07-01|
|CUS_0x1630_2023_0...| CUS_0x1630|    1|30dpd_6mob|   2023-07-01|
|CUS_0x169c_2023_0...| CUS_0x169c|    0|30dpd_6mob|   2023-07-01|
+--------------------+-----------+-----+----------+-------------+
only showing top 20 rows

In [17]:
df.printSchema()

root
 |-- loan_id: string (nullable = true)
 |-- Customer_ID: string (nullable = true)
 |-- label: integer (nullable = true)
 |-- label_def: string (nullable = true)
 |-- snapshot_date: date (nullable = true)